### ISSUE TITLE
Uni Bremen 

### ISSUE THREAD

**Issue by leon345** [RIVEK-Development/StudIP-Video-Download#5]
Hello, I would like to provide some information for the University of Bremen. 

- StudIP is hosted at https://elearning.uni-bremen.de/.
Here is a complete example URL to StuIP: https://elearning.uni-bremen.de/plugins.php/opencast/course/index/false?cid=c2156923ffead08b5eff568b44be30c5
- Opencast runs at https://opencast03.zmml.uni-bremen.de/
Here is a complete example URL to OpenCast: https://opencast03.zmml.uni-bremen.de/paella/ui/watch.html?id=8a9f1afd-7e85-4717-b2c0-a751b3ca9e06

**Comment by RIVEK-Development** [comment]
Thank you for providing this data.
I have now implemented this url paterns. New version 1.6.0 should be available soon.
Please try to use it and inform me if it is working or not.

**Comment by jholsten** [comment]
@RIVEK-Development I just tried with version 0.1.7 and unfortunately, it didn't work.

Maybe this will help: the endpoint used for fetching the URL of the MP4 file is `GET https://opencast03.zmml.uni-bremen.de/search/episode.json?id={episodeId}`. 
In the response body, the URL is located in `$search-results.$result.$mediapackage.$media.$track[0].$url`.

Here is a shortened example of the response body:
```
{
    "search-results": {
        "result": {
            "id": "{episodeId}",
            "mediapackage": {
                "id": "{episodeId}",
                "media": {
                    "track": [
                        {
                            "id": "{trackId}",
                            "mimetype": "video/mp4",
                            "url": "{resourceUrl}",
                        }
                    }
                ]
            }
        }
    }
}
```

**Comment by RIVEK-Development** [comment]
Thank you for this.

I already use this to fetch the url in background.js

There are mainly three reasons I think of why this fails

1. The json is not exactly the same as in Braunschweig because I use "resolution" and "bitrate" to choose the video. To inspect this I could use a sample json.
2. The content.js and content2.js does not get the valid id. The version 1.7.2 will log this in the console. Please check this when the update is available
3. Detecting the right university is not working at all. The UniId will be logged in the console as well.

**Comment by RIVEK-Development** [comment]
It was reason 1 there is no resolution given. Now the first video will be downloaded if no resolution is given. I got the confirmation it's working now. For all further problems please open a new issue.
